### ISSUE TITLE
solpiplog rasp pi B rev 2

### ISSUE THREAD

**Issue by alanblake** [njfaria/SolPipLog#1]
attempting to run solpiplog as root on raspberry pi model b rev 2 reports the following

An unhandled exception occurred at $0002F340:
EAccessViolation: Access violation
  $0002F340

**Comment by njfaria** [comment]
Its only working on raspberry PI 2 and 3. Sorry for late answer.
try image: https://my.pcloud.com/publink/show?code=XZnBWwZQeIyedaQJgm2dBMhDlxIT7v5uy7X
