### ISSUE TITLE
Doesn't work on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by maurangzaib** [njfaria/SolPipLog#10]
Encountered following error while running ./solpiplogstart.sh.

An unhandled exception occurred at $0002F4E4:
EAccessViolation: Access violation
  $0002F4E4

Working fine on RPi 3

**Comment by njfaria** [comment]
pi zero w version on solpiplog.tk

**Comment by njfaria** [comment]
When did you downloaded the pi zero version ? A first one did got a bug. I think the version online is working.

**Comment by maurangzaib** [comment]
I downloaded in last week. Just renamed existing solpiplog executable file
in sol folder and placed executable of pi zero version, but when run same
exception reported.

Please guide if I am missing any step.

Regards,

**Comment by maurangzaib** [comment]
Hi,

Today again I downloaded and tried to run the executable but same error. I
am attaching screenshot of error.

Please guide if I am missing any step.

Regards,

**Comment by maurangzaib** [comment]
Kindly update. I am desparate to run the software on Rpi zero.

Will appreciate your kind support.

Regards,

**Comment by njfaria** [comment]
HI. File was corrupted. Link is fixed. try again. Sorry for delay

**Comment by maurangzaib** [comment]
Hi,

It run fine and continued to upload to emoncms and pvoutput to around 1
hour. Then after program terminated with same "Segmentation Fault" error. I
executed several time but it aborts randomly giving same message.

Screen shot is attached. Kindly guide what could be the issue.

Regards,

**Comment by maurangzaib** [comment]
Also following error is reported intermittently in Debug Log window and
need to press Start button again. Check box on option "connect to inverter
on" need to click again:

04-08-2018 19:33:39 no device found-4

Please guide why the disconnection occurs intermittently by giving above
error.

Regards,

**Comment by maurangzaib** [comment]
Hi,

Kindly update as application is crashing intermittently on pi zero w by
giving "no device found-4" message. When run again it works for some time
then again gives same message. Btw I checked same on rPI 3 and it works
fine there.

Kindly guide.

Regards,
