### ISSUE TITLE
maurangzaib

### ISSUE THREAD

**Issue by maurangzaib** [njfaria/SolPipLog#14]
Hi,

The software is perfect and it works flawlessly on Voltronic Axpert VM & VM II Inverters. But it is unable to connect with Voltronic Axpert Infini 10kw inverter.

Kindly guide is it supported or not?

Regards,

**Comment by maurangzaib** [comment]
Hi,

Following error is reported in Debug window:

qpigs error: 1EStringListError List index (5) out of bounds
parseqpgs wrong size
parseqpgs wrong size
parseqpgs wrong size
parseqpgs wrong size

regards,

**Comment by salman373** [comment]
Hello.
Yes, It is working fine on Voltronic VMIII. Thanks.
I want time based change of output source priority setting. like from 8AM to 5PM it should be in SBU and after 5PM it should be SOL.
This option i have seen in ubuntu version. i want this option in pi version.
Thanks.

**Comment by salman373** [comment]
> Hi,
> 
> The software is perfect and it works flawlessly on Voltronic Axpert VM & VM II Inverters. But it is unable to connect with Voltronic Axpert Infini 10kw inverter.
> 
> Kindly guide is it supported or not?
> 
> Regards,

Yes, i am using this software with axpert VM III.

**Comment by njfaria** [comment]
> Hello.
> Yes, It is working fine on Voltronic VMIII. Thanks.
> I want time based change of output source priority setting. like from 8AM to 5PM it should be in SBU and after 5PM it should be SOL.
> This option i have seen in ubuntu version. i want this option in pi version.
> Thanks.

v2.5.5 supporting switching to SOL/SBU/UTI
