### ISSUE TITLE
Not working on Schneider SunEzy

### ISSUE THREAD

**Issue by salman373** [njfaria/SolPipLog#18]
SolPipLog Working perfect on Axpert solar and VMIII Inverter. Now i am trying to run this with Schneider SunEzy 600E Solar inverter. 
Please help me so that i can run this software with Schneider SunEzy grid tie inverter.

**Comment by njfaria** [comment]
dont know the SunEzy inverter. Is it oem brand from Axpert or Voltronic ?

**Comment by salman373** [comment]
It is not from axpert or voltronics brand.
Brand name is schneider

**Comment by njfaria** [comment]
solpiplog works only with pip ( axpert , mppsolar, easun, conversol, voltronic ) branded inverters.
