### ISSUE TITLE
Output Source Priority based on Axpert provided Voltage

### ISSUE THREAD

**Issue by zubshahid** [njfaria/SolPipLog#22]
i am running it for vmiii successfully but dont have a BMV. I am looking to modify Output Source Priority state based on the battery voltage either provided by axpert (BATT_V or BATT_CAPACITY_PERCENT) instead of BMV or an external circuit (not victron BMV).

another possibility could be to input MQTT / http request for the change in Output Source Priority  state so i can push an external value (eg. 1/2/3) to RPI for change in state from maybe Node red. thanks.

**Comment by njfaria** [comment]
just send per MQTT topic: "solpiplog/pip/status/set" payload: "uti" or "sbu"
for example: **solpiplog/pip/status/set** **uti** to switch to grid and
**solpiplog/pip/status/set sbu** to switch to **s**olar **B**atterie **U**tility
