### ISSUE TITLE
Log on node will not show valid name

### ISSUE THREAD

**Issue by Hecot** [njfaria/SolPipLog#23]
When you select log with the node instead of serialnumber, there will be no descriptive names on the inputs in emoncms - see picture.

![solpiplog](https://user-images.githubusercontent.com/11699283/65635531-cd354700-dfe0-11e9-814d-c6d42d745e3d.JPG)

**Comment by njfaria** [comment]
thats suposed to be so. on node there are no descriptions. ( compatibality issue )
