### ISSUE TITLE
FR: Controll via MQTT

### ISSUE THREAD

**Issue by cybertza** [njfaria/SolPipLog#27]
Hi I have implemented solar-sis then only recently found your project
I really like it and i am considering making a move across to it.
I like to tinker, so if you don't mind i will send you Feature requests if i think of things to better your project?

at the moment is the support to run commands via mqtt?
or to feed battery data to you via mqtt (since i already have battery watts remaining on mqtt (this is for the pylon techs that have built in BMS?

I currently use solar-sis and have the ability to add custom commands to run on the inverter
mostly what i do is use 2 features from my hass.io:
![image](https://user-images.githubusercontent.com/20600538/72830791-27da6900-3c8a-11ea-8616-08c59ce71b52.png)
This is primarily to charge the batteries to 100% from grid if i expect a utilities outage.
Further i have the following automations setup that i find helpful due to where i started:
![image](https://user-images.githubusercontent.com/20600538/72831063-b9e27180-3c8a-11ea-8e90-70a7cb570c19.png)
Inverter to Grid switched back to grid at roughly sunset -2.5 hours, i found that works for my battery setup, but i would assume one could basically do that if bat % less than 90% after set time.

Furthermore, i have set up Inverter to SBU (used to go to solar mode but started getting error 09)
and that is basically after sunrise +2 i haven't tested this metric as per say, but find it to be cutting out on early morning back and forth switching so seems to work ok.
considered doing it only after battery reaches 100% the first time for the day, but haven't fixed it since it wasn't broken ;p
![image](https://user-images.githubusercontent.com/20600538/72831398-6fadc000-3c8b-11ea-8409-a4519b0aeffd.png)

I know this is just my use case, and may only form a small part of the usage market.

I will install your latests, and test if when i get some time.

**Comment by njfaria** [comment]
with version 2.3.1 you are able to switch to grid and baterie with MQTT commands
solpiplog sends data threw MQTT about inverter status and values
see readme "value send over MQTT"
