### ISSUE TITLE
Cannot change username/password on MQTT

### ISSUE THREAD

**Issue by steverrobertson** [njfaria/SolPipLog#28]
I use this software to monitor my MPP Solar inverter through Domoticz using MQTT processed through NODE_RED, and I must say I LOVE IT!  The problem I have is this: I put in all the information in the MQTT fields and save. When my raspberry pi reboots, it can’t log into the MQTT server. When I check the settings, the username/password have defaulted to their initial values. Am I doing something wrong perhaps?
Thanks again for your hard work that is so useful!

**Comment by njfaria** [comment]
solved with version 2.3.1 please download
