### ISSUE TITLE
Raspberry Pi 3 getting error on EMONCMS: server emoncms.org not responding

### ISSUE THREAD

**Issue by salman373** [njfaria/SolPipLog#3]
Send to PVOut is working fine but getting error on send to EmonCMS. I am using my correct write key that was working fine on ICC and AICC.
Plz help me to resolve this issue. Thanks.

![solpiplog](https://cloud.githubusercontent.com/assets/27929144/25317570/84e84778-2894-11e7-88ed-c9338f41a295.PNG)

**Comment by salman373** [comment]
I have Wait one full day for EmonCms but getting the same error. Plz help me to resolve this issue.

![solpiplog2](https://cloud.githubusercontent.com/assets/27929144/25405677/6c9d145c-2a1d-11e7-9050-b7bff9d39439.PNG)

**Comment by salman373** [comment]
Can any one help me, my problem still not resolved. Solpiplog can not pushing data on emoncms.
geting error "server emoncms.org not responding."

plz help me. Thanks.

**Comment by njfaria** [comment]
how "bad" is your internet connection ?
try ping to emoncms.org. how many fails do you have ?

**Comment by salman373** [comment]
My internet is very good. please check the ping result mention below.

[image: Inline image 1]

**Comment by salman373** [comment]
![solarmonitoring](https://cloud.githubusercontent.com/assets/27929144/25870242/d8b00078-351c-11e7-9ba7-d8b8bdba85a4.PNG)

**Comment by salman373** [comment]
Issue has been resolved, it is working. Thanks for the support.
