### ISSUE TITLE
MPP Solar LV 5048 

### ISSUE THREAD

**Issue by cowpen** [njfaria/SolPipLog#31]
Hello,

I'm setting up my MPP Solar LV 5048 split phase inverter and would like to use SolPipLog to log to influxdb / grafana. I've compared the attached communication protocol for this inverter and it appears to be very similar (but not identical) to the HS_MS_MSX-Communication Protocol posted here in the docs. When you're able, could you evaluate this protocol sheet and advise as to whether it's likely to work with SolPipLog?

Thank you and kind regards.

[LV5048 5KW protocol-20190222 for customer-1.pdf](https://github.com/njfaria/SolPipLog/files/4217131/LV5048.5KW.protocol-20190222.for.customer-1.pdf)

**Comment by njfaria** [comment]
it should work. just install solpiplog. You need a raspberry pi, for that.
