### ISSUE TITLE
Vm Ubnt 18.04

### ISSUE THREAD

**Issue by cybertza** [njfaria/SolPipLog#32]
Hi I am getting the following error, Any advice, or what platform needs to be avail?

![image](https://user-images.githubusercontent.com/20600538/74873766-7a31a700-5368-11ea-966b-dec422d672e0.png)

bash: ./solpiplog: cannot execute binary file: Exec format Error

**Comment by cybertza** [comment]
i installed Debian, thinking that it may have been the issue, it was not...
![image](https://user-images.githubusercontent.com/20600538/74883729-43648c80-537a-11ea-95f3-66bd4b99d21f.png)

**Comment by cybertza** [comment]
So, i think i have tracked the problem down to the that the bin is only for ARM?

Is it possible to compile for amd64 as well?
Or use something more industry standard like docker to allow cross platform?

**Comment by njfaria** [comment]
yes its based on arm. I will compile a version for amd64. I did not played to much around with docker yet.

**Comment by cybertza** [comment]
ok thank you, looking forward to testing it then, should i load ubuntu 19.10 so long?
i can also create access for you if need be to test the pylon stuff if you are interested?

**Comment by njfaria** [comment]
feel free to try it out...
https://my.pcloud.com/publink/show?code=XZbLADkZXWVDTGOBU6XqEXKW5ykQmBfVix8k
do you got access open, for the pylon stuff ?

cybertza <notifications@github.com> escreveu no dia quinta, 20/02/2020 à(s)
14:02:

**Comment by cybertza** [comment]
Hey, Have sent you an email re Remote access for pylon stuff

**Comment by cybertza** [comment]
Thank you, the build works.

Found some minor issues :p

**Comment by uploader18** [comment]
would you compile it fir i386 debian? thanks
