### ISSUE TITLE
No longer able to get data from inverter

### ISSUE THREAD

**Issue by Bilalaerox** [njfaria/SolPipLog#33]
initially i was succeeded to get get data from my inverter. but once i restarted my PI, i am no longer getting data through pvouput.org, although the inverter connects to PI through usb but it doesn't retrieve the data.
some snaps are for your kind consideration
![image](https://user-images.githubusercontent.com/61474709/75280467-8ca35900-581e-11ea-8096-132bef13e315.png)
![image](https://user-images.githubusercontent.com/61474709/75280522-a5137380-581e-11ea-8bd0-db8af3a5b655.png)
![image](https://user-images.githubusercontent.com/61474709/75280569-be1c2480-581e-11ea-983b-1e1d09dfa26c.png)
![image](https://user-images.githubusercontent.com/61474709/75282226-bb6efe80-5821-11ea-9b00-a127a878f5d1.png)

 I will be thankful if someone points out what iam doing wrong.

**Comment by njfaria** [comment]
do you have the hybrid version ?
if not and you didnt updated the software you need to tick "single" on inverter type

**Comment by Bilalaerox** [comment]
> do you have the hybrid version ?
> if not and you didnt updated the software you need to tick "single" on inverter type

Thanks working now, But I cannot find value for PV input watts under inputs tab, Please help me to identify it.

**Comment by njfaria** [comment]
just make me a print screen of the hybrid tab
