### ISSUE TITLE
Float and Bulk voltage to feed.

### ISSUE THREAD

**Issue by Lee7and7** [njfaria/SolPipLog#36]
Hello, I would like to ask you if it will be possible to have also float and/or bulk voltage in the feed for emoncms. I'm using home assistant and need these values to setup proper automation algorithm. 
(for example I need to setup in home assistant a condition - if actual battery voltage will be near the bulk or float than do something else)
Thanks in advance
Kind Regards
Ladislav

**Comment by njfaria** [comment]
implemented
