### ISSUE TITLE
Charge and output priority 

### ISSUE THREAD

**Issue by overdrive2max** [njfaria/SolPipLog#38]
Is it possible to access the charge source priority and output source priority via MQTT or to send it to emoncms?

**Comment by njfaria** [comment]
sure:
solpiplog/pip/status/set with payload 0, 1, 2, 3 for charger settings
solpiplog/pip/status/set with payload uti, sol, sbu
 for example: **solpiplog/pip/status/set uti** to change to grid
subscribe to solpiplog/pip/status to see the status
its mentioned in the [https://github.com/njfaria/SolPipLog/blob/master/docs/mqttvalues.md](url)
last lines.. need to redo some readme... :P

**Comment by overdrive2max** [comment]
Thanks

**Comment by sixxxis** [comment]
changing to output priority works
changing charger settings not
