### ISSUE TITLE
"pip not found on /dev/ttyUSB0" with SolPipLog 1.5.0 ...

### ISSUE THREAD

**Issue by dourix** [njfaria/SolPipLog#4]
Hi, 
Error: “pip not found on /dev/ttyUSB0” )
The same config is working fine with version 1.4.8.
Env: Raspberry pi3, RS232, Axpert 5KVA
Thanks in advance
![capture solpiplog150 nok](https://user-images.githubusercontent.com/31487959/29891110-a2095204-8dd2-11e7-9157-ee1ca8558228.PNG)

**Comment by xenonshop** [comment]
Same issue for me, version 1.4.8 works fine.

**Comment by salman373** [comment]
I am having Same Issue with 1.5.0 and works fine 1.4.8.
Error is pinot found on /dev/ttyUSB0...

Please help to resolve the issue.

Regards,

**Comment by njfaria** [comment]
i should realy look more at github comments...
new version is going to be online.... stay online.....

**Comment by salman373** [comment]
Thanks.

**Comment by dourix** [comment]
fixed in v2.0.0; many thanks !
