### ISSUE TITLE
MQTT not starting correctly on wifi disconnect with 2.4.0

### ISSUE THREAD

**Issue by PoloB12** [njfaria/SolPipLog#40]
Hi, when my wifi disconnects, MQTT stops broadcasting. Activate and deactivate MQTT is enough to start it again. Any way to automate this ?

**Comment by efkostya** [comment]
confirm. I have a similar problem

**Comment by njfaria** [comment]
looking for solution... simulating it.

**Comment by PoloB12** [comment]
By the way ; PVOutput continues normally and emoncms too, it's only MQTT that seems to be affected.

**Comment by efkostya** [comment]
I temporarily solved the problem by installing mosquitto on the same raspberry and specifying localhost as the broker's mqtt address. 
Local Mosquitto configured the bridge mode to the server broker. This way it works fine. When I configure solpiplog to the server address directly-if the ping or connection is lost-mqtt itself is not restored, although sending data to pvonline does not stop.

**Comment by PoloB12** [comment]
> I temporarily solved the problem by installing mosquitto on the same raspberry and specifying localhost as the broker's mqtt address.
> Local Mosquitto configured the bridge mode to the server broker. This way it works fine. When I configure solpiplog to the server address directly-if the ping or connection is lost-mqtt itself is not restored, although sending data to pvonline does not stop.

That's a smart solution, will look into that untill there's a final fix, thanks!

**Comment by njfaria** [comment]
please try the new version... 
need feedback if it works with your configuration.

**Comment by efkostya** [comment]
Thank you! I installed the new version, set it up on a remote mqtt  server, and wait.. still working

**Comment by PoloB12** [comment]
Yes, it looks like the problem is solved after some quick testing with the 2.5 version. Thanks !

**Comment by efkostya** [comment]
works fine thanks!
