### ISSUE TITLE
Pylontech MQTT values incorrect

### ISSUE THREAD

**Issue by overdrive2max** [njfaria/SolPipLog#41]
Good day
Thank you for an awesome project. It has saved me many hours of completing my own project.
The pylontech functionality is most welcome but I have an issue.
Values for Pack1 current, voltage remainah are correct but watt, voltage, current, remainah are incorrect as per attached photo.
![image](https://user-images.githubusercontent.com/12275134/81021004-6e835600-8e6a-11ea-9bbd-775b5188b34e.png)

**Comment by njfaria** [comment]
ok, i see the issue. You got only one pylon pack.
so the values are wrong...
looking at it.

**Comment by njfaria** [comment]
fixed. i hope ;) new version online

**Comment by overdrive2max** [comment]
Thank you. will test shortly. Have a lovely day
