### ISSUE TITLE
Chahne charger settings from mqtt not working 

### ISSUE THREAD

**Issue by efkostya** [njfaria/SolPipLog#42]
`solpiplog/pip/status/set with payload 0, 1, 2, 3 for charger settings`
not working. 
Nothing happens when sending a value.

**Comment by eddee54455** [comment]
Use "solpiplog/pip/charge/set" with payload 0,1,2,3 for the charger
settings... There is a minor typo in the instructions...

Ed

**Comment by efkostya** [comment]
thank you very much, it's working.
