### ISSUE TITLE
Support for Axpert 7.2 MAX

### ISSUE THREAD

**Issue by jeblond** [njfaria/SolPipLog#51]
These inverters have 2 mppt chargers and they dont show  up in solpiplog, or the total PV power, it only shows 1 MPPT charger

**Comment by njfaria** [comment]
onother new one... 
i may see to it only if i got acces to your raspberry...
rgb lights ? what the heck....?!?

**Comment by jeblond** [comment]
Sure. send me your email address for vnc cloud

**Comment by njfaria** [comment]
solpiplog at gmail.com

jeblond <notifications@github.com> escreveu no dia quinta, 29/10/2020 à(s)
22:10:

**Comment by njfaria** [comment]
implemented axpert pip 7248max on new release
