### ISSUE TITLE
Deye/Sunsynk support

### ISSUE THREAD

**Issue by ojeysky** [njfaria/SolPipLog#57]
I recently changed from axpert to Deye and was wondering if this can be included as well. The operating principle for Deye should work for other variants like Sunsynk and Sol-Ark

**Comment by njfaria** [comment]
we are in contact per PM

**Comment by pfostenberg** [comment]
Hi, what is the state? want also to change from MPPSolar MAX 8048 to DEYE SUN 8KW Single Phase. And would like to stay with SolPipLog -:)
