### ISSUE TITLE
AutoStart

### ISSUE THREAD

**Issue by salman373** [njfaria/SolPipLog#6]
i want to auto start the Solpiplog with saved configurations. is it possible to autorun this app when pi restart on any error e.g low voltage or any other issue ?

**Comment by dourix** [comment]
will be great indeed...

**Comment by njfaria** [comment]
i am going to publish a new version with autostart. i will publish a link with the image, and a readme how to install autostart for the ones who dont care about images.
github does not alow big files, or is there any other solution ???

**Comment by salman373** [comment]
Thank you very much.
Please also add error logs. e.g. low voltage, low battery etc. error and error date and time.
Thanks.
Did you publish the autostart link as i did not find this on github.
Thanks.

**Comment by dourix** [comment]
looks working fine; many thanks !
