### ISSUE TITLE
MQTT QPIGS2 output

### ISSUE THREAD

**Issue by cybersyx** [njfaria/SolPipLog#61]
Hi, this application is awesome. I send the data to an mqtt server without problems but as I could read from the documentation via mqtt it does not send the data of a second mppt (qpigs2). Is it possible to add this function? Thanks a lot !

**Comment by njfaria** [comment]
need to add it

**Comment by diybuc** [comment]
V3.0 seems to log my QPIGS2 once then it shows 0 for all values.
If i manually send QPIGS2 i get this reply
inverter model: 30
68 2D
neue version:QPIGS2h-
size : 9
02.8 248.7 00713

![qpigsMAIN](https://user-images.githubusercontent.com/46763270/117564856-6fb71680-b0ae-11eb-9269-fbcf71051bf2.PNG)
![QPIGS2debugW](https://user-images.githubusercontent.com/46763270/117564873-92e1c600-b0ae-11eb-9a8e-5f1c1f2890b3.PNG)
It is A V W
The only issue is under the main Windows it show QPIGS2 all 0 as values

It worked Flawless on the previous version of the Inverter but after a upgrade to the inverter it stopped.

**Comment by njfaria** [comment]
will soon post the version which logs QPIGS2

**Comment by njfaria** [comment]
@cybersyx @diybuc  version 3.1.1 online

**Comment by diybuc** [comment]
You are the man. It is working a charm and I now realize how much Wh went
Mia due to my estimate calculation. I will make a small donation soon.
Thanks bud.
