### ISSUE TITLE
support infinisolar / mppsolar 10k and Sacred SUN BMS

### ISSUE THREAD

**Issue by Lucano99** [njfaria/SolPipLog#62]
Hello,

I have a question, if you think your SolPipLog will be able to read data from MPP Solar and Sacred SUN Lithium BMS - https://www.sacredsun.com/Product/Battery/2020/1117/Energy-Storage-Lithium.html ?

Thank you!

**Comment by njfaria** [comment]
reading data from MPPSolar is supported, then SUN Lithium i dont know.
