### ISSUE TITLE
QPIGS2 values not logging.

### ISSUE THREAD

**Issue by diybuc** [njfaria/SolPipLog#64]
When I send QPIGS 2 command via Debug Window it reports the values for PV2. But on the Main Windows all values are 0.

Answer on Debug Window
68 2D
neue version:QPIGS2h-
size : 9
00.9 236.9 00222 

Values on Main Windows under QPIGS2
All 0

The reporting to Emoncms is also showing 
41 PV2    8 hrs   23342 
PV2 V      8 hrs   50.144 
PV2 W     8 hrs   229.6
Logged once 8 hrs ago. (Unsure what causes it to log once and then stop as a reboot of the Pi3 makes no difference and not logging again.

I tried setting the inverter type to Single, Hybrid and Parallel to check but no change.

The rest of the Values update on time all the time.

Changed Permission to 777 for all files in SOL but makes no difference. Also set permissions the same on SOL directory.

I even upgraded the Inverter MAX8 to version U1-90-03 and the Remote Panel to 12.10 with no change.
On FW version 46.05 it reported on QPIGS2 debug
size : 9             
02.7 099.6 00274     
parseqpgs wrong size

**Comment by diybuc** [comment]
Not sure if this migh help.
If i launch Solpiplog from terminal as root this error Pops up in the Terminal.
(solpiplog:2377): Pango-WARNING **: 08:48:31.521: Invalid UTF-8 string passed to pango_layout_set_text()

**Comment by njfaria** [comment]
i will post soon a version that logs QPIGS2

**Comment by diybuc** [comment]
Awesome, Thank you that will solve a lot of my headaches. If you need Someone to do Testing don't Hesitate to ask me to do it!

**Comment by njfaria** [comment]
@diybuc version 3.1.1 out that supports QPIGS2
