### ISSUE TITLE
Idea: Command line only version 

### ISSUE THREAD

**Issue by mdhemmi** [njfaria/SolPipLog#7]
Hello,

would be possible to create a command line only version where you can define the output in a config file. For example output to Emoncms, influxdb or even a text file.

Thanks
hemmi

**Comment by solucionesmipc** [comment]
+1

**Comment by abc2006** [comment]
Yeah, i miss this right now!
Would support you for that feature...

**Comment by njfaria** [comment]
new version is sending some values over MQTT.
more flexible than sending to a text file.

**Comment by mdhemmi** [comment]
Thanks for MQTT much appreciated. Would be great if your application could run on an RPI without desktop as a service.

**Comment by GeirTS** [comment]
Is it possible to add all of the inverterdata (qpigs) as MQTT-values

**Comment by njfaria** [comment]
sending more values as MQTT on version v2.5.5.20190802

**Comment by kxn25** [comment]
When is the Releas planed?

**Comment by jmanley** [comment]
I realise this ticket's been closed, but I don't see a cli option in the current version.  This feature would be very handy for me, too.  Is the conclusion that this feature will not be implemented?
