### ISSUE TITLE
QPIGS2 is not sent via MQTT 

### ISSUE THREAD

**Issue by ArminK1337** [njfaria/SolPipLog#73]
QPIGS is sent over MQTT and QPIGS2 is not.

**Comment by ArminK1337** [comment]
QPIGS2 it´s showing on SolPipLog but not send over MQTT

**Comment by ArminK1337** [comment]
<img width="1140" alt="Screenshot 2022-02-13 172114" src="https://user-images.githubusercontent.com/99137755/153762536-551d5f2f-e3b4-48a5-8ba7-9f634e225289.png">
<img width="785" alt="Screenshot 2022-02-13 172210" src="https://user-images.githubusercontent.com/99137755/153762537-66b2efa7-d328-4ab9-91e6-46f347d4bb50.png">

**Comment by ArminK1337** [comment]
ja dann kann man sich auch auf deutsch unterhalten :D

**Comment by ArminK1337** [comment]
Perfekt Daten werden jetzt übertragen :D Vielen Vielen Dank und mega Software, bin sehr zufrieden :D

**Comment by ArminK1337** [comment]
Okay ich hab nen Bug gefunden bei der  3.2.0 ist ja auch ne "Beta" Sobald es die Ladequellen Priorität umstellen will von "Solar" auf "Solar and Utility" stürzt die ganze Software ab.

**Comment by njfaria** [comment]
womit ? per MQTT oder interface ? komplett absturz ist natürlich extrem...

**Comment by ArminK1337** [comment]
Bei beidem, spielt keine Rolle

**Comment by njfaria** [comment]
mail mich mal an solpiplog at gmail.com
